# Generated by Django 4.2.25 on 2025-11-03 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='frankfurter', max_length=20)),
            ],
            options={
                'db_table': 'exchange_rates',
                'ordering': ['-date', '-timestamp'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency', 'date'], name='exchange_ra_base_cu_8d841e_idx'), models.Index(fields=['base_currency', 'date'], name='exchange_ra_base_cu_f3dd3d_idx'), models.Index(fields=['timestamp'], name='exchange_ra_timesta_efcd56_idx')],
                'unique_together': {('base_currency', 'target_currency', 'date')},
            },
        ),
    ]
